### ISSUE TITLE
FTSize is not disposing

### ISSUE THREAD

**Issue by Kittiepryde** [Robmaister/SharpFont#43]
I kind of just guessed my way through rendering a spritefont and then rendering text to the screen.

using (FTSize ftSize = face.Size)
{

	int height = ftSize.Metrics.NominalHeight;
	height -= glyph.freeTypeGlyph.Metrics.HorizontalBearingY / 64;
	// freeTypeGlyph is GlyphSlot
	// glyph is a class that holds the spriteFont character locations

	var position = new XnaFramework.Vector2 (dx, dy + height);
	// spriteBatch drawing here
}

I've also tried calling ftSize.Dispose(), and testing the IsDisposed() flag (it tests true).
I'm not sure if I'm abusing FTSize in anyway.  Is there another way to get the Nominal Height that I need?

I have a current version of the library off GitHub.  I compiled it with Xamarin studio, targeting .Net 2.0 \ x86.  I am using the freetype6.dll from the GitHub.

**Comment by Robmaister** [comment]
I took a glance at how FTSize gets disposed, looks pretty clearly like all of the instances generated by face.Size are never removed from the internal tracking lists since `userAlloc == false`.

I moved the de-registration with the parent face outside of the `if (userAlloc && !duplicate)` section since it shouldn't have been in there.

If for some reason the issue persists, let me know.
