### ISSUE TITLE
Crash with SharpFont 2.5.3.0 on Win7x64 with OpenRA

### ISSUE THREAD

**Issue by reaperrr** [Robmaister/SharpFont#48]
Had this reproducable crash with SharpFont 2.5.3.0 right at launch with https://github.com/OpenRA/OpenRA on Win7x64.
SharpFont 2.5.0.1 works fine.

Crash log:
Tiberian Dawn Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18444
Exception of type `System.TypeInitializationException`: Der Typeninitialisierer für "OpenRA.Graphics.SpriteFont" hat eine Ausnahme verursacht.
Inner Exception of type `System.DllNotFoundException`: Die DLL "freetype6.dll": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
  TypeName=``
     bei SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   bei SharpFont.Library..ctor()
   bei OpenRA.Graphics.SpriteFont..cctor() in e:\OpenRA_work2\OpenRA.Game\Graphics\SpriteFont.cs:Zeile 22.
   bei OpenRA.Graphics.SpriteFont..ctor(String name, Int32 size)
   bei OpenRA.Graphics.Renderer.<InitializeFonts>b__1(KeyValuePair`2 x) in e:\OpenRA_work2\OpenRA.Game\Graphics\Renderer.cs:Zeile 95.
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   bei OpenRA.Graphics.Renderer.InitializeFonts(Manifest m) in e:\OpenRA_work2\OpenRA.Game\Graphics\Renderer.cs:Zeile 94.
   bei OpenRA.Game.InitializeMod(String mod, Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 303.
   bei OpenRA.Game.Initialize(Arguments args) in e:\OpenRA_work2\OpenRA.Game\Game.cs:Zeile 261.
   bei OpenRA.Program.Run(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:Zeile 108.
   bei OpenRA.Program.Main(String[] args) in e:\OpenRA_work2\OpenRA.Game\Support\Program.cs:Zeile 39.

**Comment by Robmaister** [comment]
@reaperrr  Out of curiosity, did the new redistributable link I posted above fix the issue?

@Mailaender I'm going to get a new version of SharpFont out in the next few days. I implemented structs for all of the fixed-point types, which is a breaking change. I'm going to bump up to 3.0.0 (to start following semver instead of mirroring FreeType numbers) and also fork OpenRA to fix the breaking changes (which are only changing instances of `advance.X >> 6` to `(int)advance.X` and so on).

Is calling wget/curl in the bash script and `Invoke-WebRequest` in the powershell script fine (for fetch-thirdparty-deps)? That way you wouldn't be tied to whichever version of FreeType I pack into the nuget package (though that version will try and be the most compatible)

**Comment by Mailaender** [comment]
Maybe do it like SDL2 and create a *.redist nuget package for the native libraries and depend on that. Might be easier to maintain than hotlinked downloads.

**Comment by reaperrr** [comment]
@Robmaister Sorry for replying this late, I kept delaying/forgetting to test it.
Yes, the VC++ 2013 redist fixes the issue.

**Comment by Mailaender** [comment]
https://www.nuget.org/packages/lua51.redist/5.1.5 ships both v110 and v120 compiled in separate folders. Compare https://github.com/OpenRA/OpenRA/pull/7579 which seems to be essentially the same thing.

**Comment by Robmaister** [comment]
Awesome! I'll try and find some time this weekend to package everything correctly, and also make a pull request to update all of the breaking API changes since the last release

**Comment by Mailaender** [comment]
I just uploaded https://www.nuget.org/packages/freetype2.redist/2.4.11 which is using ancient build dependencies to avoid complicated dependency installation for end users.

**Comment by Mailaender** [comment]
We just found out that Windows 7 only comes with msvc100 by default.

**Comment by Robmaister** [comment]
Configuring a SharpFont.Dependencies package right now, going to include x86 and x64 builds for MSVC90,100,110, and 120 (or at least attempt to)

**Comment by Mailaender** [comment]
You may want to add https://www.nuget.org/packages/zlib.redist/ as a dependency.

**Comment by Robmaister** [comment]
Just published [3.0.0-beta](https://www.nuget.org/packages/SharpFont/3.0.0-beta), along with [SharpFont.Dependencies](https://www.nuget.org/packages/SharpFont.Dependencies/) storing all of builds of FreeType2. Going to go through all of the issues that are still open and try to fix everything before final release.

Also I'm building with just the internal version of zlib since that's the way FreeType compiles by default. If you want one that dynamically links with zlib.dll, let me know and we can work on some way of making it work

**Comment by Mailaender** [comment]
I had to do several re-releases of https://www.nuget.org/packages/freetype2.redist/ as you need an exact version of the Zlib library so my bundling kinda defeats the purpose. Statically linking it seems a better idea here then.

**Comment by Mailaender** [comment]
@reaperrr Can you test if https://github.com/OpenRA/OpenRA/pull/7696 works for you?

**Comment by Robmaister** [comment]
Should be resolved now with SharpFont 3.0.0+ and the separate SharpFont.Dependencies package.

**Comment by BrisingrAerowing** [comment]
@Mailaender I compile statically-linked all-deps versions of Freetype. I currently only have Visual Studio 2015 installed (I had to refresh Windows 10 because of Nvidia testing in production and crashing on startup), but I have copies of VS 2008 - 2013 I can install as well.

I am planning on doing that and providing builds for this project again, anyways.

The dependencies I use are: zlib, libbz2, libpng16, and harfbuzz. I can also do various other combinations if needed. They don't take very long on my laptop (I just compiled Mesa3d in under a minute, whereas my old Sony Vaio Ultrabook took 30+ minutes to do that, and Freetype compiles in about the same amount of time)

**Comment by HinTak** [comment]
The freetype dependencies is straight from fedora linux, but I keep freetype more up to date than fedora provides - besides, win64 needs extra patch:
https://github.com/HinTak/Font-Validator/tree/master/bin/Win32
https://github.com/HinTak/Font-Validator/tree/master/bin/Win64
also there are two duplicate freetype dll's named slightly differently, to satisfy circular dependency with harfbuzz and what SharpFont expects.
