### ISSUE TITLE
Library.PropertySet and Get on int type.

### ISSUE THREAD

**Issue by HinTak** [Robmaister/SharpFont#82]
Does not seem to be able to do "Library.PropertySet<int>(...)". Specifically, I am trying to do:

```
                int ipv = 35;
                _lib.PropertySet<int>("truetype", "interpreter-version", ipv);
```

or something of that sort. 

```

System.ArgumentNullException: Value cannot be null.
Parameter name: dst
  at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal:StructureToPtr (object,intptr,bool)
  at System.Runtime.InteropServices.Marshal.StructureToPtr[T] (System.Runtime.InteropServices.T structure, IntPtr ptr, Boolean fDeleteOld) <0x40a312b0 + 0x00043> in <filename unknown>:0 
```

Marshalling of value type of System.Int32 gets in the way. I tried explicitly boxing, etc.

I am going unsafe code and explicitly getting at &int  and manually calling FT.FT_Property_Set to get around this...

**Comment by HinTak** [comment]
To get the current setting,

```
_lib.PropertyGet<int>("truetype", "interpreter-version", ipv);
```

does not work either!

**Comment by HinTak** [comment]
This seems to work, for setting:

```
int a = 40;
fixed (int *b = &a) {
IntPtr c = new IntPtr(b);
_lib.PropertySet("truetype", "interpreter-version", c);
}
```

**Comment by HinTak** [comment]
I cannot seem to be able to Marshal the return value:

```
IntPtr c = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(System.Int32)));
_lib.PropertyGet("truetype", "interpreter-version", out c);
//Console.WriteLine(Marshal.ReadIntPtr(c));
//var deref = (int)Marshal.PtrToStructure(c, typeof(System.Int32));
//Console.WriteLine(deref);
```

I think either 'Marshal.ReadIntPtr' or 'Marshal.PtrToStructure(c, typeof(System.Int32))' should work? Neither of them does.

**Comment by HinTak** [comment]
I'll just let you get on with it now - my workaround for blindly setting works (comfirmed by the other side on the C Freetype end), so I am not looking further on getting on the C# side.

One day I would like Get on C# to work somehow too.

**Comment by HinTak** [comment]
I have fixed the Set part. Have not figured out the Get part yet.

**Comment by HinTak** [comment]
BTW,

```
_lib.PropertyGet<int>("truetype", "interpreter-version", ipv);
```

should almost always returns 35, when/if you get it to work correctly. 38 are available as alternatives for special build of freetype older than 2.6.4 . 40 is the new default in 2.6.4, but switchable back to 35. (and 38 is available for special non-default build of freetype). I need to be able to switch between 35 and one of the other two.

**Comment by Robmaister** [comment]
I properly implemented PropertySet<T> for ints via `GCHandle`, don't believe I can do the same for PropertyGet<T> (GCHandle pins a copy of the int value on the heap, can't find a way to copy back to the original T value for all value types and structs). Fix for this is inbound sometime today.

**Comment by Robmaister** [comment]
I read further into Marshal.PtrToStructure documentation, it does in fact work with value types, you just have to use the overload that takes a System.Type instead of an object, which returns a boxed copy of the value.

The way I've set it up, all of the overloads chain off to the IntPtr overload, which is the only one that actually calls FT.FT_Property_Set. I'm using the following code to test. I'm behind on the freetype Windows builds, so I can't bump the number up to 40, FreeType instead returns a not implemented error code. Still, I can read the value out, write it back, and read it out again and it stays the same. The VS memory debugger shows that I am in fact passing a pointer to the correct value into FreeType.

	Library lib = new Library();

	int interpreterVer;
	lib.PropertyGet<int>("truetype", "interpreter-version", out interpreterVer);
	Console.WriteLine("Initial get: " + interpreterVer);

	interpreterVer = 40;
	Console.WriteLine("Setting value to: " + interpreterVer);

	lib.PropertySet<int>("truetype", "interpreter-version", ref interpreterVer);
	Console.WriteLine("After set: " + interpreterVer);

	lib.PropertyGet<int>("truetype", "interpreter-version", out interpreterVer);
	Console.WriteLine("Verification get: " + interpreterVer);

I would appreciate if you could test this code and make sure it works for other properties. I still need to catch up with API changes and MSVC builds for all 2.6.x and 2.7.x versions of freetype.

**Comment by HinTak** [comment]
Yes, the `interpreter-version` thing was introduced around 2.6.3 or 2.6.4; you need a build later than that to change between 35 and 40 (and also 38 if you build it specially).

**Comment by HinTak** [comment]
Just notice a warning from mono's compiler concerning this change:

`SharpFont/Source/SharpFontShared/Library.cs(469,15): warning CS3006: Overloaded method `SharpFont.Library.PropertySet<T>(string, string, T)' differing only in ref or out, or in array rank, is not CLS-compliant
		SharpFont/Source/SharpFontShared/Library.cs(449,15): (Location of the symbol related to previous warning)
``

```

**Comment by Robmaister** [comment]
ah yes, that's not actually a problem. The overloading is just for convenience so I'll throw a `[CLSCompliant(false)]` there.

Thanks for the catch!

**Comment by HinTak** [comment]
Hmm, I think the warning is for people to rethink whether they really want both versions. Do you need both?

**Comment by Robmaister** [comment]
It's a common pattern to include both - ref/out is faster, passing by value is cleaner.

It's particularly cleaner when you're trying to pass in a property from a class (since you can't `ref` a property), because you'd have to create a temporary variable to copy the property to before passing it by ref. The non-ref overload handles this for you.

OpenTK does this, but typically there's a return value to differ on. There are some cases where there are functions that act this same way that were marked obsolete in favor of static functions that do the same thing but differ on return type, however we don't have a return type to differ on, so I'd prefer to just mark the non-ref version as not CLS compliant and move on.

One example off the top of my head is all of the OpenTK linear algebra classes: https://github.com/opentk/opentk/blob/develop/src/OpenTK/Math/Matrix4.cs#L597

**Comment by HinTak** [comment]
I'll be testing this against mingw-build of freetype 2.8.x for windows as well as on mono/linux in the next few days; so assuming things go well, this can close.
